version: '3'

services:
  jenkins:
    image: deweiliu/jenkins:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: jenkins-container
    ports:
      - 80:80
