AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FileSystemResource:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: jenkins-home

Outputs:
  FileSystemResource:
    Value: !Ref FileSystemResource
    Export: 
      Name: JenkinsFileSystem
