AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  JenkinsDockerImage:
    Type: String
    Default: jenkins/jenkins:latest
    Description: Docker image used in the ECS task definition. Override the default to use a custom image (mandatory).
Description:
  Provision the required resources for blog post example 'Deploying Jenkins to ECS'.
  Wait for creation to complete before testing.
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAM
    Properties:
      TemplateURL: https://dewei-artifacts.s3.eu-west-2.amazonaws.com/jenkins/vpc.yml
      Parameters:
        VPC: !ImportValue Core-Vpc
        InternetGateway: !ImportValue Core-InternetGateway

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-artifacts.s3.eu-west-2.amazonaws.com/jenkins/iam.yml
      Parameters:
        JenkinsFileSystem: !ImportValue Jenkins-EfsId

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-artifacts.s3.eu-west-2.amazonaws.com/jenkins/ecs.yml
      Parameters:
        JenkinsDockerImage: !Ref JenkinsDockerImage
        MasterRole: !GetAtt IAM.Outputs.MasterRole
        ECSExecutionRole: !GetAtt IAM.Outputs.ECSExecutionRole
        JenkinsFileSystem: !ImportValue Jenkins-EfsId
        VPC: !ImportValue Core-Vpc
        MasterSubnet1: !GetAtt VPC.Outputs.MasterSubnet1
        SlavesSubnet1: !GetAtt VPC.Outputs.SlavesSubnet1
        MasterSubnet2: !GetAtt VPC.Outputs.MasterSubnet2
        SlavesSubnet2: !GetAtt VPC.Outputs.SlavesSubnet2

Outputs:
  Domain:
    Value: !GetAtt ECS.Outputs.JenkinsCNameRecord
    Export:
      Name: JenkinsDNSName
  JenkinsLogs:
    Value: !GetAtt ECS.Outputs.Logs
    Export:
      Name: JenkinsLogs
