AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  JenkinsDockerImage:
    Type: String
    Default: deweiliu/jenkins:latest
    Description: Docker image used in the ECS task definition. Override the default to use a custom image (mandatory).
Description:
  Provision the required resources for blog post example 'Deploying Jenkins to ECS'.
  Wait for creation to complete before testing.
Resources:
  ArtifactStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/artiffact-storage.yml
  CertificateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/certificate.yml
  ECSStack: # This is EFS stack
    Type: AWS::CloudFormation::Stack
    Description: EFS Stack (not ECS stack)
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/efs-ecs.yml
      Parameters:
        JenkinsDockerImage: !Ref JenkinsDockerImage
        CertificateArn: !GetAtt CertificateStack.Outputs.CertificateARN

  RealECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/efs-ecs.yml
      Parameters:
        JenkinsDockerImage: !Ref JenkinsDockerImage
        CertificateArn: !GetAtt CertificateStack.Outputs.CertificateARN



  CNametack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/cname.yml
      Parameters:
        LoadBalancerDNSName: !GetAtt ECSStack.Outputs.LoadBalancerDNSName
  IAMBuildtack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/iam-build.yml

  IAMDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/iam-deploy.yml
  IAMEC2PluginStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dewei-jenkins.s3.eu-west-2.amazonaws.com/iam-ec2-plugin.yml

Outputs:
  JenkinsLoadBalancerDNS:
    Value: !GetAtt CNametack.Outputs.CName
