AWSTemplateFormatVersion: 2010-09-09

Resources:
  BuildArtifactS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dewei-artifacts

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      DeletionPolicy: Retain
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: jenkins-home

Outputs:
  FileSystemID:
    Value: !Ref FileSystem
    Export:
      Name: Jenkins-EfsId
  FileSystemArn:
    Value: !GetAtt FileSystem.Arn
    Export:
      Name: Jenkins-EfsArn
  BuildArtifactS3:
    Value: !Ref BuildArtifactS3
    Export:
      Name: BuildArtifactS3
