AWSTemplateFormatVersion: 2010-09-09

Resources:
  BuildArtifactS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dewei-artifacts

  FileSystemResource:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: jenkins-home

Outputs:
  FileSystemResource:
    Value: !Ref FileSystemResource
    Export:
      Name: JenkinsFileSystem
  BuildArtifactS3:
    Value: !Ref BuildArtifactS3
    Export:
      Name: BuildArtifactS3
