pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }

    options {
        timeout(time: 90, unit: 'MINUTES')
    }

    stages {
        stage('Destroy Jenkins Service') {
            steps {
                sh "aws cloudformation delete-stack --region eu-west-2 --stack-name Jenkins"
            }
        }

        stage('Terminate Current Jenkins Agent'){
            steps{
                sh "aws ec2 terminate-instances --region eu-west-2 --instance-ids $(curl http://169.254.169.254/latest/meta-data/instance-id)"
            }
        }
    }
}
