AWSTemplateFormatVersion: 2010-09-09

Resources:

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: jenkins-home

  SlaveSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.3.0/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: "AWS::Region"
      Tags:
        - Key: Name
          Value: jenkins-slave-subnet

  SlaveSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.3.16/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: "AWS::Region"
      Tags:
        - Key: Name
          Value: jenkins-slave-subnet

Outputs:
  FileSystemID:
    Value: !Ref FileSystem
    Export:
      Name: Jenkins-EfsId
  FileSystemArn:
    Value: !GetAtt FileSystem.Arn
    Export:
      Name: Jenkins-EfsArn
  SlaveSubnet1:
    Value: !Ref SlaveSubnet1
    Export:
      Name: Jenkins-SlaveSubnet1
  SlaveSubnet0:
    Value: !Ref SlaveSubnet0
    Export:
      Name: Jenkins-SlaveSubnet0
