AWSTemplateFormatVersion: 2010-09-09

Parameters:
  JenkinsFileSystem:
    Type: String

Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jenkins-ecs-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  MasterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jenkins-master-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: AccessFileSystem
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                Resource: !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${JenkinsFileSystem}
        - PolicyName: JenkinsEC2PluginPolicy
          PolicyDocument:
            Statement:
              Action:
                - ec2:DescribeSpotInstanceRequests
                - ec2:CancelSpotInstanceRequests
                - ec2:GetConsoleOutput
                - ec2:RequestSpotInstances
                - ec2:RunInstances
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:TerminateInstances
                - ec2:CreateTags
                - ec2:DeleteTags
                - ec2:DescribeInstances
                - ec2:DescribeKeyPairs
                - ec2:DescribeRegions
                - ec2:DescribeImages
                - ec2:DescribeAvailabilityZones
                - ec2:DescribeSecurityGroups
                - ec2:DescribeSubnets
                - iam:ListInstanceProfilesForRole
                - iam:PassRole
                - ec2:GetPasswordData
              Effect: Allow
              Resource: "*"

  BuilderSlaveRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jenkins-build-slave-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AmazonS3FullAccess
      #   - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      #   - arn:aws:iam::aws:policy/AmazonECS_FullAccess
      #   - arn:aws:iam::aws:policy/AmazonVPCFullAccess
      #   - arn:aws:iam::aws:policy/IAMFullAccess
      #   - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  BuilderSlaveInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: jenkins-builder-slave
      Roles:
        - !Ref BuilderSlaveRole

Outputs:
  ECSExecutionRole:
    Value: !GetAtt ECSExecutionRole.Arn
  MasterRole:
    Value: !GetAtt MasterRole.Arn
  BuilderSlaveInstanceProfile:
    Value: !GetAtt BuilderSlaveInstanceProfile.Arn
